name: Release

on:
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  DOCKER_REGISTRY: ghcr.io


jobs:

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v1.2

      - name: Publish docker image with hash
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}

      - name: Publish docker image with tag
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ env.GIT_TAG_NAME }}

      - name: Collect artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir dist
          DOCKER_IMAGE=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}
          docker run --rm -v ./dist:/dist --entrypoint=sh $DOCKER_IMAGE -c "cp /usr/bin/corsanywhere /dist/corsanywhere"

      - uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: artifact-binary
          path: dist
          overwrite: true


  publish-github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true

      - name: Check
        run: |
          ls -R

      - name: Hash file
        run: |
          (sha256sum * | tee sha256sums.txt)

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*

  clean-artifacts:
    name: Clean artifacts
    runs-on: ubuntu-latest
    needs: [publish-github-release]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: artifact-*
